version: '3'
services:
  byoai-agent:
    build: .
    environment:
      - CONTEXT_WORKFLOW_DIR=/app/workflows
      - CONTEXT_AGENT_PORT=8000
      - CONTEXT_AGENT_HOST=0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./workflows:/app/workflows
